// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {project} from '../models';
import {params} from '../models';
import {venue} from '../models';

export function AddAudioFiles(arg1:Array<string>):Promise<Array<main.SourceInfo>>;

export function ApplySoundPreset(arg1:project.Project,arg2:string):Promise<project.Project>;

export function ApplyVenue(arg1:project.Project,arg2:string):Promise<project.Project>;

export function CancelJob(arg1:string):Promise<void>;

export function ChooseExportPath():Promise<string>;

export function ChooseProjectSavePath():Promise<string>;

export function ChooseProjectToOpen():Promise<string>;

export function DeleteSoundPreset(arg1:string):Promise<void>;

export function GetPeaks(arg1:string,arg2:number):Promise<Array<number>>;

export function ListParams():Promise<Array<params.ParamSpec>>;

export function ListSoundPresets():Promise<Array<project.SoundPresetInfo>>;

export function ListVenues():Promise<Array<venue.Preset>>;

export function LoadProject(arg1:string):Promise<project.Project>;

export function NewProject():Promise<project.Project>;

export function OpenAudioFiles():Promise<Array<main.SourceInfo>>;

export function RenderOriginal(arg1:project.Project,arg2:number,arg3:number):Promise<string>;

export function RenderPreview(arg1:project.Project,arg2:number,arg3:number):Promise<string>;

export function SaveProject(arg1:string,arg2:project.Project):Promise<void>;

export function SaveSoundPreset(arg1:string,arg2:project.Project):Promise<void>;

export function SeparateSource(arg1:string):Promise<string>;

export function StartExport(arg1:project.Project,arg2:string):Promise<string>;

export function StemSeparationAvailable():Promise<boolean>;
