// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAudioFiles(arg1) {
  return window['go']['main']['App']['AddAudioFiles'](arg1);
}

export function ApplySoundPreset(arg1, arg2) {
  return window['go']['main']['App']['ApplySoundPreset'](arg1, arg2);
}

export function ApplyVenue(arg1, arg2) {
  return window['go']['main']['App']['ApplyVenue'](arg1, arg2);
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function ChooseExportPath() {
  return window['go']['main']['App']['ChooseExportPath']();
}

export function ChooseProjectSavePath() {
  return window['go']['main']['App']['ChooseProjectSavePath']();
}

export function ChooseProjectToOpen() {
  return window['go']['main']['App']['ChooseProjectToOpen']();
}

export function DeleteSoundPreset(arg1) {
  return window['go']['main']['App']['DeleteSoundPreset'](arg1);
}

export function GetPeaks(arg1, arg2) {
  return window['go']['main']['App']['GetPeaks'](arg1, arg2);
}

export function ListParams() {
  return window['go']['main']['App']['ListParams']();
}

export function ListSoundPresets() {
  return window['go']['main']['App']['ListSoundPresets']();
}

export function ListVenues() {
  return window['go']['main']['App']['ListVenues']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function NewProject() {
  return window['go']['main']['App']['NewProject']();
}

export function OpenAudioFiles() {
  return window['go']['main']['App']['OpenAudioFiles']();
}

export function RenderOriginal(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderOriginal'](arg1, arg2, arg3);
}

export function RenderPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderPreview'](arg1, arg2, arg3);
}

export function SaveProject(arg1, arg2) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2);
}

export function SaveSoundPreset(arg1, arg2) {
  return window['go']['main']['App']['SaveSoundPreset'](arg1, arg2);
}

export function StartExport(arg1, arg2) {
  return window['go']['main']['App']['StartExport'](arg1, arg2);
}
